sudo: required
language: generic

services:
  - docker

before_install:
  - docker run -e CI=true USERNAME/react-test npm test -- --coverage

script:
  - docker run -e CI=true danlan26/react-test npm test -- 

after_success:
  - docker build -t danlan26/multi-client ./client
  - docker build -t danlan26/multi-nginx ./nginx
  - docker build -t danlan26/multi-server ./server
  - docker build -t danlan26/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push danlan26/multi-client
  - docker push danlan26/multi-nginx
  - docker push danlan26/multi-server
  - docker push danlan26/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
